manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: smart-toggle
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 241ff39556b3685c9344c4c22fd9a655af8eb3ba # 0.2.1
      import: app/west.yml
    - name: zmk-smart-toggle
      remote: smart-toggle
      revision: fd05108600a66a88b9e03263cc132721d89b9ffb
  self:
    path: config
