manifest:
  remotes:
    - name: pipex
      url-base: https://github.com/pipex
  projects:
    - name: zmk
      remote: pipex
      revision: 3b056cde4f0a72616d1d257d444c3f74c6df6bc3
      import: app/west.yml
  self:
    path: config

