manifest:
  remotes:
    - name: pipex
      url-base: https://github.com/pipex
  projects:
    - name: zmk
      remote: pipex
      revision: 8854da339d082494c98085f3c0e8f869210e538d
      import: app/west.yml
  self:
    path: config

