manifest:
  remotes:
    - name: pipex
      url-base: https://github.com/pipex
  projects:
    - name: zmk
      remote: pipex
      revision: a7062f761f0c5fce9b86916da74000aa4c704c02
      import: app/west.yml
  self:
    path: config

